# Generated by Django 3.0.3 on 2020-05-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_auto_20200517_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
