# Generated by Django 3.0.3 on 2020-05-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0003_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
    ]
