# Generated by Django 3.0.3 on 2020-05-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
