# Generated by Django 3.0.2 on 2020-01-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaproductimage',
            name='image',
            field=models.ImageField(upload_to='pizzas_images/'),
        ),
    ]
