# Generated by Django 3.0.2 on 2020-01-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_products', '0002_auto_20200123_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
