# Generated by Django 3.0.3 on 2020-05-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_products', '0007_auto_20200514_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_comment',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pizza_products.PizzaProduct'),
        ),
    ]
